/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { GET as GET_ai_____path_ } from "../app/api/ai/[...path]/route";
import type { POST as POST_ai_____path_ } from "../app/api/ai/[...path]/route";

// Type-only representation of your API routes
export type APIRouter = {
  ai: {
    "[...path]": {
      get: typeof GET_ai_____path_;
      post: typeof POST_ai_____path_;
    };
  };
};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/ai/[...path]",
    methods: ["GET", "POST"],
  },
] as const;
